### ISSUE TITLE
Broken download_url link in setup.py

### ISSUE THREAD

**Issue by scop** [dbtsai/python-mimeparse#18]
PyPI has changed the formatting of the tarball download links, and the one in setup.py is now broken:
https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package

I would have suggested to use github tag URL there instead and submitted a PR, but unfortunately it looks like the python-mimeparse releases are not being tagged in the repository...

**Comment by wojcikstefan** [comment]
Hi @scop, thanks for pointing that out! I could create a `1.5.2` tag for the current master and point the `download_url` to `https://github.com/dbtsai/python-mimeparse/tarball/1.5.2`. Is there anything else that would need to be done?

**Comment by scop** [comment]
I think that would work (if for nothing else, would be nice to have the tags around :)).

But then again, I don't know what is the expected semantics for the `download_url` in the first place; is it expected to be even versioned? Some other (unversioned) choices to consider:
https://github.com/dbtsai/python-mimeparse/releases
https://pypi.python.org/pypi/python-mimeparse/

**Comment by wojcikstefan** [comment]
@scop that should do it :)
